export const SECTION_TYPES = [
  "hero",
  "intro",
  "services",
  "servicesGrid",
  "servicesAccordion",
  "servicesCTA",
  "servicesLicensing",
  "coursesCatalog",
  "whyChoose",
  "investment",
  "clientLogos",
  "cta",
  "contact",
  "aboutHero",
  "aboutOverview",
  "aboutIntro",
  "aboutCTA",
  "aboutMission",
  "aboutLeadership",
  "aboutInquiry",
  "aboutFooter",
  "aboutRegulatory",
  "aboutVisionMission",
  "aboutFramework",
  "aboutAdvantage",
  "aboutValues",
  "homeIncubationHighlight",
  "incubation",
  "globalStandards",
  "homeAbout",
  "homeServicesGrid",
  "homeProductCategories",
  "homeTrustedBy",
  "homeQuickInquiry",
  "homeWhyChoose",
  "servicesPageHero",
  "servicesCapabilityCards",
  "servicesSpecialized",
  "servicesProductCatalog",
  "servicesRegulatory",
  "servicesFooter",
  "clientsPageHero",
  "clientsSectors",
  "clientsCompliance",
  "clientsTrustedBy",
  "clientsPartnerCta",
  "productsCatalogShowcase",
  "productsFooter",
  "contactHero",
  "contactInquiry",
  "servicesHero",
  "industriesHero",
  "industriesGrid",
  "industriesCta",
  "researchHub",
  "projectsHero",
  "projectsGrid",
  "projectsIntegrity",
  "projectsPartners",
] as const;

export type SectionType = (typeof SECTION_TYPES)[number];

export type PageSection = {
  id: string;
  type: SectionType;
  order: number;
  data: Record<string, unknown>;
};
